apiVersion: v1
name: fsx-chart
description: A Helm chart for the ACK service controller for Amazon FSx (FSx)
version: 0.0.0-non-release-version
appVersion: 0.0.0-non-release-version
home: https://github.com/aws-controllers-k8s/fsx-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/fsx-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: FSx Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/fsx-maintainer
keywords:
  - aws
  - kubernetes
  - fsx
