// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ActiveDirectoryErrorType string

const (
	ActiveDirectoryErrorType_DOMAIN_NOT_FOUND         ActiveDirectoryErrorType = "DOMAIN_NOT_FOUND"
	ActiveDirectoryErrorType_INCOMPATIBLE_DOMAIN_MODE ActiveDirectoryErrorType = "INCOMPATIBLE_DOMAIN_MODE"
	ActiveDirectoryErrorType_INVALID_DOMAIN_STAGE     ActiveDirectoryErrorType = "INVALID_DOMAIN_STAGE"
	ActiveDirectoryErrorType_INVALID_NETWORK_TYPE     ActiveDirectoryErrorType = "INVALID_NETWORK_TYPE"
	ActiveDirectoryErrorType_WRONG_VPC                ActiveDirectoryErrorType = "WRONG_VPC"
)

type AdministrativeActionType string

const (
	AdministrativeActionType_DOWNLOAD_DATA_FROM_BACKUP        AdministrativeActionType = "DOWNLOAD_DATA_FROM_BACKUP"
	AdministrativeActionType_FILE_SYSTEM_ALIAS_ASSOCIATION    AdministrativeActionType = "FILE_SYSTEM_ALIAS_ASSOCIATION"
	AdministrativeActionType_FILE_SYSTEM_ALIAS_DISASSOCIATION AdministrativeActionType = "FILE_SYSTEM_ALIAS_DISASSOCIATION"
	AdministrativeActionType_FILE_SYSTEM_UPDATE               AdministrativeActionType = "FILE_SYSTEM_UPDATE"
	AdministrativeActionType_IOPS_OPTIMIZATION                AdministrativeActionType = "IOPS_OPTIMIZATION"
	AdministrativeActionType_MISCONFIGURED_STATE_RECOVERY     AdministrativeActionType = "MISCONFIGURED_STATE_RECOVERY"
	AdministrativeActionType_RELEASE_NFS_V3_LOCKS             AdministrativeActionType = "RELEASE_NFS_V3_LOCKS"
	AdministrativeActionType_SNAPSHOT_UPDATE                  AdministrativeActionType = "SNAPSHOT_UPDATE"
	AdministrativeActionType_STORAGE_OPTIMIZATION             AdministrativeActionType = "STORAGE_OPTIMIZATION"
	AdministrativeActionType_STORAGE_TYPE_OPTIMIZATION        AdministrativeActionType = "STORAGE_TYPE_OPTIMIZATION"
	AdministrativeActionType_THROUGHPUT_OPTIMIZATION          AdministrativeActionType = "THROUGHPUT_OPTIMIZATION"
	AdministrativeActionType_VOLUME_INITIALIZE_WITH_SNAPSHOT  AdministrativeActionType = "VOLUME_INITIALIZE_WITH_SNAPSHOT"
	AdministrativeActionType_VOLUME_RESTORE                   AdministrativeActionType = "VOLUME_RESTORE"
	AdministrativeActionType_VOLUME_UPDATE                    AdministrativeActionType = "VOLUME_UPDATE"
	AdministrativeActionType_VOLUME_UPDATE_WITH_SNAPSHOT      AdministrativeActionType = "VOLUME_UPDATE_WITH_SNAPSHOT"
)

type AliasLifecycle string

const (
	AliasLifecycle_AVAILABLE     AliasLifecycle = "AVAILABLE"
	AliasLifecycle_CREATE_FAILED AliasLifecycle = "CREATE_FAILED"
	AliasLifecycle_CREATING      AliasLifecycle = "CREATING"
	AliasLifecycle_DELETE_FAILED AliasLifecycle = "DELETE_FAILED"
	AliasLifecycle_DELETING      AliasLifecycle = "DELETING"
)

type AutoImportPolicyType string

const (
	AutoImportPolicyType_NEW                 AutoImportPolicyType = "NEW"
	AutoImportPolicyType_NEW_CHANGED         AutoImportPolicyType = "NEW_CHANGED"
	AutoImportPolicyType_NEW_CHANGED_DELETED AutoImportPolicyType = "NEW_CHANGED_DELETED"
	AutoImportPolicyType_NONE                AutoImportPolicyType = "NONE"
)

type AutocommitPeriodType string

const (
	AutocommitPeriodType_DAYS    AutocommitPeriodType = "DAYS"
	AutocommitPeriodType_HOURS   AutocommitPeriodType = "HOURS"
	AutocommitPeriodType_MINUTES AutocommitPeriodType = "MINUTES"
	AutocommitPeriodType_MONTHS  AutocommitPeriodType = "MONTHS"
	AutocommitPeriodType_NONE    AutocommitPeriodType = "NONE"
	AutocommitPeriodType_YEARS   AutocommitPeriodType = "YEARS"
)

type BackupLifecycle string

const (
	BackupLifecycle_AVAILABLE    BackupLifecycle = "AVAILABLE"
	BackupLifecycle_COPYING      BackupLifecycle = "COPYING"
	BackupLifecycle_CREATING     BackupLifecycle = "CREATING"
	BackupLifecycle_DELETED      BackupLifecycle = "DELETED"
	BackupLifecycle_FAILED       BackupLifecycle = "FAILED"
	BackupLifecycle_PENDING      BackupLifecycle = "PENDING"
	BackupLifecycle_TRANSFERRING BackupLifecycle = "TRANSFERRING"
)

type BackupType string

const (
	BackupType_AUTOMATIC      BackupType = "AUTOMATIC"
	BackupType_AWS_BACKUP     BackupType = "AWS_BACKUP"
	BackupType_USER_INITIATED BackupType = "USER_INITIATED"
)

type DataCompressionType string

const (
	DataCompressionType_LZ4  DataCompressionType = "LZ4"
	DataCompressionType_NONE DataCompressionType = "NONE"
)

type DataRepositoryLifecycle string

const (
	DataRepositoryLifecycle_AVAILABLE     DataRepositoryLifecycle = "AVAILABLE"
	DataRepositoryLifecycle_CREATING      DataRepositoryLifecycle = "CREATING"
	DataRepositoryLifecycle_DELETING      DataRepositoryLifecycle = "DELETING"
	DataRepositoryLifecycle_FAILED        DataRepositoryLifecycle = "FAILED"
	DataRepositoryLifecycle_MISCONFIGURED DataRepositoryLifecycle = "MISCONFIGURED"
	DataRepositoryLifecycle_UPDATING      DataRepositoryLifecycle = "UPDATING"
)

type DataRepositoryTaskFilterName string

const (
	DataRepositoryTaskFilterName_data_repository_association_id DataRepositoryTaskFilterName = "data-repository-association-id"
	DataRepositoryTaskFilterName_file_cache_id                  DataRepositoryTaskFilterName = "file-cache-id"
	DataRepositoryTaskFilterName_file_system_id                 DataRepositoryTaskFilterName = "file-system-id"
	DataRepositoryTaskFilterName_task_lifecycle                 DataRepositoryTaskFilterName = "task-lifecycle"
)

type DataRepositoryTaskLifecycle string

const (
	DataRepositoryTaskLifecycle_CANCELED  DataRepositoryTaskLifecycle = "CANCELED"
	DataRepositoryTaskLifecycle_CANCELING DataRepositoryTaskLifecycle = "CANCELING"
	DataRepositoryTaskLifecycle_EXECUTING DataRepositoryTaskLifecycle = "EXECUTING"
	DataRepositoryTaskLifecycle_FAILED    DataRepositoryTaskLifecycle = "FAILED"
	DataRepositoryTaskLifecycle_PENDING   DataRepositoryTaskLifecycle = "PENDING"
	DataRepositoryTaskLifecycle_SUCCEEDED DataRepositoryTaskLifecycle = "SUCCEEDED"
)

type DataRepositoryTaskType string

const (
	DataRepositoryTaskType_AUTO_RELEASE_DATA               DataRepositoryTaskType = "AUTO_RELEASE_DATA"
	DataRepositoryTaskType_EXPORT_TO_REPOSITORY            DataRepositoryTaskType = "EXPORT_TO_REPOSITORY"
	DataRepositoryTaskType_IMPORT_METADATA_FROM_REPOSITORY DataRepositoryTaskType = "IMPORT_METADATA_FROM_REPOSITORY"
	DataRepositoryTaskType_RELEASE_DATA_FROM_FILESYSTEM    DataRepositoryTaskType = "RELEASE_DATA_FROM_FILESYSTEM"
)

type DeleteFileSystemOpenZFSOption string

const (
	DeleteFileSystemOpenZFSOption_DELETE_CHILD_VOLUMES_AND_SNAPSHOTS DeleteFileSystemOpenZFSOption = "DELETE_CHILD_VOLUMES_AND_SNAPSHOTS"
)

type DeleteOpenZFSVolumeOption string

const (
	DeleteOpenZFSVolumeOption_DELETE_CHILD_VOLUMES_AND_SNAPSHOTS DeleteOpenZFSVolumeOption = "DELETE_CHILD_VOLUMES_AND_SNAPSHOTS"
)

type DiskIOPSConfigurationMode string

const (
	DiskIOPSConfigurationMode_AUTOMATIC        DiskIOPSConfigurationMode = "AUTOMATIC"
	DiskIOPSConfigurationMode_USER_PROVISIONED DiskIOPSConfigurationMode = "USER_PROVISIONED"
)

type DriveCacheType string

const (
	DriveCacheType_NONE DriveCacheType = "NONE"
	DriveCacheType_READ DriveCacheType = "READ"
)

type EventType string

const (
	EventType_CHANGED EventType = "CHANGED"
	EventType_DELETED EventType = "DELETED"
	EventType_NEW     EventType = "NEW"
)

type FileCacheLifecycle string

const (
	FileCacheLifecycle_AVAILABLE FileCacheLifecycle = "AVAILABLE"
	FileCacheLifecycle_CREATING  FileCacheLifecycle = "CREATING"
	FileCacheLifecycle_DELETING  FileCacheLifecycle = "DELETING"
	FileCacheLifecycle_FAILED    FileCacheLifecycle = "FAILED"
	FileCacheLifecycle_UPDATING  FileCacheLifecycle = "UPDATING"
)

type FileCacheLustreDeploymentType string

const (
	FileCacheLustreDeploymentType_CACHE_1 FileCacheLustreDeploymentType = "CACHE_1"
)

type FileCacheType string

const (
	FileCacheType_LUSTRE FileCacheType = "LUSTRE"
)

type FileSystemLifecycle string

const (
	FileSystemLifecycle_AVAILABLE                 FileSystemLifecycle = "AVAILABLE"
	FileSystemLifecycle_CREATING                  FileSystemLifecycle = "CREATING"
	FileSystemLifecycle_DELETING                  FileSystemLifecycle = "DELETING"
	FileSystemLifecycle_FAILED                    FileSystemLifecycle = "FAILED"
	FileSystemLifecycle_MISCONFIGURED             FileSystemLifecycle = "MISCONFIGURED"
	FileSystemLifecycle_MISCONFIGURED_UNAVAILABLE FileSystemLifecycle = "MISCONFIGURED_UNAVAILABLE"
	FileSystemLifecycle_UPDATING                  FileSystemLifecycle = "UPDATING"
)

type FileSystemMaintenanceOperation string

const (
	FileSystemMaintenanceOperation_BACKING_UP FileSystemMaintenanceOperation = "BACKING_UP"
	FileSystemMaintenanceOperation_PATCHING   FileSystemMaintenanceOperation = "PATCHING"
)

type FileSystemType string

const (
	FileSystemType_LUSTRE  FileSystemType = "LUSTRE"
	FileSystemType_ONTAP   FileSystemType = "ONTAP"
	FileSystemType_OPENZFS FileSystemType = "OPENZFS"
	FileSystemType_WINDOWS FileSystemType = "WINDOWS"
)

type FilterName string

const (
	FilterName_backup_type          FilterName = "backup-type"
	FilterName_data_repository_type FilterName = "data-repository-type"
	FilterName_file_cache_id        FilterName = "file-cache-id"
	FilterName_file_cache_type      FilterName = "file-cache-type"
	FilterName_file_system_id       FilterName = "file-system-id"
	FilterName_file_system_type     FilterName = "file-system-type"
	FilterName_volume_id            FilterName = "volume-id"
)

type FlexCacheEndpointType string

const (
	FlexCacheEndpointType_CACHE  FlexCacheEndpointType = "CACHE"
	FlexCacheEndpointType_NONE   FlexCacheEndpointType = "NONE"
	FlexCacheEndpointType_ORIGIN FlexCacheEndpointType = "ORIGIN"
)

type InputOntapVolumeType string

const (
	InputOntapVolumeType_DP InputOntapVolumeType = "DP"
	InputOntapVolumeType_RW InputOntapVolumeType = "RW"
)

type LustreAccessAuditLogLevel string

const (
	LustreAccessAuditLogLevel_DISABLED   LustreAccessAuditLogLevel = "DISABLED"
	LustreAccessAuditLogLevel_ERROR_ONLY LustreAccessAuditLogLevel = "ERROR_ONLY"
	LustreAccessAuditLogLevel_WARN_ERROR LustreAccessAuditLogLevel = "WARN_ERROR"
	LustreAccessAuditLogLevel_WARN_ONLY  LustreAccessAuditLogLevel = "WARN_ONLY"
)

type LustreDeploymentType string

const (
	LustreDeploymentType_PERSISTENT_1 LustreDeploymentType = "PERSISTENT_1"
	LustreDeploymentType_PERSISTENT_2 LustreDeploymentType = "PERSISTENT_2"
	LustreDeploymentType_SCRATCH_1    LustreDeploymentType = "SCRATCH_1"
	LustreDeploymentType_SCRATCH_2    LustreDeploymentType = "SCRATCH_2"
)

type LustreReadCacheSizingMode string

const (
	LustreReadCacheSizingMode_NO_CACHE                            LustreReadCacheSizingMode = "NO_CACHE"
	LustreReadCacheSizingMode_PROPORTIONAL_TO_THROUGHPUT_CAPACITY LustreReadCacheSizingMode = "PROPORTIONAL_TO_THROUGHPUT_CAPACITY"
	LustreReadCacheSizingMode_USER_PROVISIONED                    LustreReadCacheSizingMode = "USER_PROVISIONED"
)

type MetadataConfigurationMode string

const (
	MetadataConfigurationMode_AUTOMATIC        MetadataConfigurationMode = "AUTOMATIC"
	MetadataConfigurationMode_USER_PROVISIONED MetadataConfigurationMode = "USER_PROVISIONED"
)

type NetworkType string

const (
	NetworkType_DUAL NetworkType = "DUAL"
	NetworkType_IPV4 NetworkType = "IPV4"
)

type NfsVersion string

const (
	NfsVersion_NFS3 NfsVersion = "NFS3"
)

type OntapDeploymentType string

const (
	OntapDeploymentType_MULTI_AZ_1  OntapDeploymentType = "MULTI_AZ_1"
	OntapDeploymentType_MULTI_AZ_2  OntapDeploymentType = "MULTI_AZ_2"
	OntapDeploymentType_SINGLE_AZ_1 OntapDeploymentType = "SINGLE_AZ_1"
	OntapDeploymentType_SINGLE_AZ_2 OntapDeploymentType = "SINGLE_AZ_2"
)

type OntapFileSystemUserType string

const (
	OntapFileSystemUserType_UNIX    OntapFileSystemUserType = "UNIX"
	OntapFileSystemUserType_WINDOWS OntapFileSystemUserType = "WINDOWS"
)

type OntapVolumeType string

const (
	OntapVolumeType_DP OntapVolumeType = "DP"
	OntapVolumeType_LS OntapVolumeType = "LS"
	OntapVolumeType_RW OntapVolumeType = "RW"
)

type OpenZFSCopyStrategy string

const (
	OpenZFSCopyStrategy_CLONE            OpenZFSCopyStrategy = "CLONE"
	OpenZFSCopyStrategy_FULL_COPY        OpenZFSCopyStrategy = "FULL_COPY"
	OpenZFSCopyStrategy_INCREMENTAL_COPY OpenZFSCopyStrategy = "INCREMENTAL_COPY"
)

type OpenZFSDataCompressionType string

const (
	OpenZFSDataCompressionType_LZ4  OpenZFSDataCompressionType = "LZ4"
	OpenZFSDataCompressionType_NONE OpenZFSDataCompressionType = "NONE"
	OpenZFSDataCompressionType_ZSTD OpenZFSDataCompressionType = "ZSTD"
)

type OpenZFSDeploymentType string

const (
	OpenZFSDeploymentType_MULTI_AZ_1     OpenZFSDeploymentType = "MULTI_AZ_1"
	OpenZFSDeploymentType_SINGLE_AZ_1    OpenZFSDeploymentType = "SINGLE_AZ_1"
	OpenZFSDeploymentType_SINGLE_AZ_2    OpenZFSDeploymentType = "SINGLE_AZ_2"
	OpenZFSDeploymentType_SINGLE_AZ_HA_1 OpenZFSDeploymentType = "SINGLE_AZ_HA_1"
	OpenZFSDeploymentType_SINGLE_AZ_HA_2 OpenZFSDeploymentType = "SINGLE_AZ_HA_2"
)

type OpenZFSFileSystemUserType string

const (
	OpenZFSFileSystemUserType_POSIX OpenZFSFileSystemUserType = "POSIX"
)

type OpenZFSQuotaType string

const (
	OpenZFSQuotaType_GROUP OpenZFSQuotaType = "GROUP"
	OpenZFSQuotaType_USER  OpenZFSQuotaType = "USER"
)

type OpenZFSReadCacheSizingMode string

const (
	OpenZFSReadCacheSizingMode_NO_CACHE                            OpenZFSReadCacheSizingMode = "NO_CACHE"
	OpenZFSReadCacheSizingMode_PROPORTIONAL_TO_THROUGHPUT_CAPACITY OpenZFSReadCacheSizingMode = "PROPORTIONAL_TO_THROUGHPUT_CAPACITY"
	OpenZFSReadCacheSizingMode_USER_PROVISIONED                    OpenZFSReadCacheSizingMode = "USER_PROVISIONED"
)

type PrivilegedDelete string

const (
	PrivilegedDelete_DISABLED             PrivilegedDelete = "DISABLED"
	PrivilegedDelete_ENABLED              PrivilegedDelete = "ENABLED"
	PrivilegedDelete_PERMANENTLY_DISABLED PrivilegedDelete = "PERMANENTLY_DISABLED"
)

type ReportFormat string

const (
	ReportFormat_REPORT_CSV_20191124 ReportFormat = "REPORT_CSV_20191124"
)

type ReportScope string

const (
	ReportScope_FAILED_FILES_ONLY ReportScope = "FAILED_FILES_ONLY"
)

type ResourceType string

const (
	ResourceType_FILE_SYSTEM ResourceType = "FILE_SYSTEM"
	ResourceType_VOLUME      ResourceType = "VOLUME"
)

type RestoreOpenZFSVolumeOption string

const (
	RestoreOpenZFSVolumeOption_DELETE_CLONED_VOLUMES         RestoreOpenZFSVolumeOption = "DELETE_CLONED_VOLUMES"
	RestoreOpenZFSVolumeOption_DELETE_INTERMEDIATE_SNAPSHOTS RestoreOpenZFSVolumeOption = "DELETE_INTERMEDIATE_SNAPSHOTS"
)

type RetentionPeriodType string

const (
	RetentionPeriodType_DAYS        RetentionPeriodType = "DAYS"
	RetentionPeriodType_HOURS       RetentionPeriodType = "HOURS"
	RetentionPeriodType_INFINITE    RetentionPeriodType = "INFINITE"
	RetentionPeriodType_MINUTES     RetentionPeriodType = "MINUTES"
	RetentionPeriodType_MONTHS      RetentionPeriodType = "MONTHS"
	RetentionPeriodType_SECONDS     RetentionPeriodType = "SECONDS"
	RetentionPeriodType_UNSPECIFIED RetentionPeriodType = "UNSPECIFIED"
	RetentionPeriodType_YEARS       RetentionPeriodType = "YEARS"
)

type S3AccessPointAttachmentLifecycle string

const (
	S3AccessPointAttachmentLifecycle_AVAILABLE     S3AccessPointAttachmentLifecycle = "AVAILABLE"
	S3AccessPointAttachmentLifecycle_CREATING      S3AccessPointAttachmentLifecycle = "CREATING"
	S3AccessPointAttachmentLifecycle_DELETING      S3AccessPointAttachmentLifecycle = "DELETING"
	S3AccessPointAttachmentLifecycle_FAILED        S3AccessPointAttachmentLifecycle = "FAILED"
	S3AccessPointAttachmentLifecycle_MISCONFIGURED S3AccessPointAttachmentLifecycle = "MISCONFIGURED"
	S3AccessPointAttachmentLifecycle_UPDATING      S3AccessPointAttachmentLifecycle = "UPDATING"
)

type S3AccessPointAttachmentType string

const (
	S3AccessPointAttachmentType_ONTAP   S3AccessPointAttachmentType = "ONTAP"
	S3AccessPointAttachmentType_OPENZFS S3AccessPointAttachmentType = "OPENZFS"
)

type S3AccessPointAttachmentsFilterName string

const (
	S3AccessPointAttachmentsFilterName_file_system_id S3AccessPointAttachmentsFilterName = "file-system-id"
	S3AccessPointAttachmentsFilterName_type           S3AccessPointAttachmentsFilterName = "type"
	S3AccessPointAttachmentsFilterName_volume_id      S3AccessPointAttachmentsFilterName = "volume-id"
)

type SecurityStyle string

const (
	SecurityStyle_MIXED SecurityStyle = "MIXED"
	SecurityStyle_NTFS  SecurityStyle = "NTFS"
	SecurityStyle_UNIX  SecurityStyle = "UNIX"
)

type ServiceLimit string

const (
	ServiceLimit_FILE_CACHE_COUNT                         ServiceLimit = "FILE_CACHE_COUNT"
	ServiceLimit_FILE_SYSTEM_COUNT                        ServiceLimit = "FILE_SYSTEM_COUNT"
	ServiceLimit_STORAGE_VIRTUAL_MACHINES_PER_FILE_SYSTEM ServiceLimit = "STORAGE_VIRTUAL_MACHINES_PER_FILE_SYSTEM"
	ServiceLimit_TOTAL_IN_PROGRESS_COPY_BACKUPS           ServiceLimit = "TOTAL_IN_PROGRESS_COPY_BACKUPS"
	ServiceLimit_TOTAL_SSD_IOPS                           ServiceLimit = "TOTAL_SSD_IOPS"
	ServiceLimit_TOTAL_STORAGE                            ServiceLimit = "TOTAL_STORAGE"
	ServiceLimit_TOTAL_THROUGHPUT_CAPACITY                ServiceLimit = "TOTAL_THROUGHPUT_CAPACITY"
	ServiceLimit_TOTAL_USER_INITIATED_BACKUPS             ServiceLimit = "TOTAL_USER_INITIATED_BACKUPS"
	ServiceLimit_TOTAL_USER_TAGS                          ServiceLimit = "TOTAL_USER_TAGS"
	ServiceLimit_VOLUMES_PER_FILE_SYSTEM                  ServiceLimit = "VOLUMES_PER_FILE_SYSTEM"
)

type SnaplockType string

const (
	SnaplockType_COMPLIANCE SnaplockType = "COMPLIANCE"
	SnaplockType_ENTERPRISE SnaplockType = "ENTERPRISE"
)

type SnapshotFilterName string

const (
	SnapshotFilterName_file_system_id SnapshotFilterName = "file-system-id"
	SnapshotFilterName_volume_id      SnapshotFilterName = "volume-id"
)

type SnapshotLifecycle string

const (
	SnapshotLifecycle_AVAILABLE SnapshotLifecycle = "AVAILABLE"
	SnapshotLifecycle_CREATING  SnapshotLifecycle = "CREATING"
	SnapshotLifecycle_DELETING  SnapshotLifecycle = "DELETING"
	SnapshotLifecycle_PENDING   SnapshotLifecycle = "PENDING"
)

type Status string

const (
	Status_CANCELLED          Status = "CANCELLED"
	Status_COMPLETED          Status = "COMPLETED"
	Status_FAILED             Status = "FAILED"
	Status_IN_PROGRESS        Status = "IN_PROGRESS"
	Status_OPTIMIZING         Status = "OPTIMIZING"
	Status_PAUSED             Status = "PAUSED"
	Status_PENDING            Status = "PENDING"
	Status_UPDATED_OPTIMIZING Status = "UPDATED_OPTIMIZING"
)

type StorageType string

const (
	StorageType_HDD                 StorageType = "HDD"
	StorageType_INTELLIGENT_TIERING StorageType = "INTELLIGENT_TIERING"
	StorageType_SSD                 StorageType = "SSD"
)

type StorageVirtualMachineFilterName string

const (
	StorageVirtualMachineFilterName_file_system_id StorageVirtualMachineFilterName = "file-system-id"
)

type StorageVirtualMachineLifecycle string

const (
	StorageVirtualMachineLifecycle_CREATED       StorageVirtualMachineLifecycle = "CREATED"
	StorageVirtualMachineLifecycle_CREATING      StorageVirtualMachineLifecycle = "CREATING"
	StorageVirtualMachineLifecycle_DELETING      StorageVirtualMachineLifecycle = "DELETING"
	StorageVirtualMachineLifecycle_FAILED        StorageVirtualMachineLifecycle = "FAILED"
	StorageVirtualMachineLifecycle_MISCONFIGURED StorageVirtualMachineLifecycle = "MISCONFIGURED"
	StorageVirtualMachineLifecycle_PENDING       StorageVirtualMachineLifecycle = "PENDING"
)

type StorageVirtualMachineRootVolumeSecurityStyle string

const (
	StorageVirtualMachineRootVolumeSecurityStyle_MIXED StorageVirtualMachineRootVolumeSecurityStyle = "MIXED"
	StorageVirtualMachineRootVolumeSecurityStyle_NTFS  StorageVirtualMachineRootVolumeSecurityStyle = "NTFS"
	StorageVirtualMachineRootVolumeSecurityStyle_UNIX  StorageVirtualMachineRootVolumeSecurityStyle = "UNIX"
)

type StorageVirtualMachineSubtype string

const (
	StorageVirtualMachineSubtype_DEFAULT          StorageVirtualMachineSubtype = "DEFAULT"
	StorageVirtualMachineSubtype_DP_DESTINATION   StorageVirtualMachineSubtype = "DP_DESTINATION"
	StorageVirtualMachineSubtype_SYNC_DESTINATION StorageVirtualMachineSubtype = "SYNC_DESTINATION"
	StorageVirtualMachineSubtype_SYNC_SOURCE      StorageVirtualMachineSubtype = "SYNC_SOURCE"
)

type TieringPolicyName string

const (
	TieringPolicyName_ALL           TieringPolicyName = "ALL"
	TieringPolicyName_AUTO          TieringPolicyName = "AUTO"
	TieringPolicyName_NONE          TieringPolicyName = "NONE"
	TieringPolicyName_SNAPSHOT_ONLY TieringPolicyName = "SNAPSHOT_ONLY"
)

type Unit string

const (
	Unit_DAYS Unit = "DAYS"
)

type UpdateOpenZFSVolumeOption string

const (
	UpdateOpenZFSVolumeOption_DELETE_CLONED_VOLUMES         UpdateOpenZFSVolumeOption = "DELETE_CLONED_VOLUMES"
	UpdateOpenZFSVolumeOption_DELETE_INTERMEDIATE_DATA      UpdateOpenZFSVolumeOption = "DELETE_INTERMEDIATE_DATA"
	UpdateOpenZFSVolumeOption_DELETE_INTERMEDIATE_SNAPSHOTS UpdateOpenZFSVolumeOption = "DELETE_INTERMEDIATE_SNAPSHOTS"
)

type VolumeFilterName string

const (
	VolumeFilterName_file_system_id             VolumeFilterName = "file-system-id"
	VolumeFilterName_storage_virtual_machine_id VolumeFilterName = "storage-virtual-machine-id"
)

type VolumeLifecycle string

const (
	VolumeLifecycle_AVAILABLE     VolumeLifecycle = "AVAILABLE"
	VolumeLifecycle_CREATED       VolumeLifecycle = "CREATED"
	VolumeLifecycle_CREATING      VolumeLifecycle = "CREATING"
	VolumeLifecycle_DELETING      VolumeLifecycle = "DELETING"
	VolumeLifecycle_FAILED        VolumeLifecycle = "FAILED"
	VolumeLifecycle_MISCONFIGURED VolumeLifecycle = "MISCONFIGURED"
	VolumeLifecycle_PENDING       VolumeLifecycle = "PENDING"
)

type VolumeStyle string

const (
	VolumeStyle_FLEXGROUP VolumeStyle = "FLEXGROUP"
	VolumeStyle_FLEXVOL   VolumeStyle = "FLEXVOL"
)

type VolumeType string

const (
	VolumeType_ONTAP   VolumeType = "ONTAP"
	VolumeType_OPENZFS VolumeType = "OPENZFS"
)

type WindowsAccessAuditLogLevel string

const (
	WindowsAccessAuditLogLevel_DISABLED            WindowsAccessAuditLogLevel = "DISABLED"
	WindowsAccessAuditLogLevel_FAILURE_ONLY        WindowsAccessAuditLogLevel = "FAILURE_ONLY"
	WindowsAccessAuditLogLevel_SUCCESS_AND_FAILURE WindowsAccessAuditLogLevel = "SUCCESS_AND_FAILURE"
	WindowsAccessAuditLogLevel_SUCCESS_ONLY        WindowsAccessAuditLogLevel = "SUCCESS_ONLY"
)

type WindowsDeploymentType string

const (
	WindowsDeploymentType_MULTI_AZ_1  WindowsDeploymentType = "MULTI_AZ_1"
	WindowsDeploymentType_SINGLE_AZ_1 WindowsDeploymentType = "SINGLE_AZ_1"
	WindowsDeploymentType_SINGLE_AZ_2 WindowsDeploymentType = "SINGLE_AZ_2"
)
